    name: Build & Deploy Microservice Bank branches
    on:
      push:
        branches:
          - main
    jobs:
      build-deploy:
        name: build and deploy first job
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v3

          - name: setup JDK 17
            uses: actions/setup-java@v3
            with:
              distributions: 'corretto'
              java-version: 17

          - name: Unit Tests
            run: mvn -B test --file pom.xml

          - name: Build the application
            run:  |
              mvn clean
              mvn -B package --file pom.xml
